### ISSUE TITLE
Customizable DNS Configuration

### ISSUE THREAD

**Issue by bonedaddy** [MASQ-Project/Node#283]
# Overview

DNS is hard coded to port 53, which means if it conflicts with a locally running  port,  you have to stop the service, or build a docker image. I also dont want to  use docker as it makes security management more difficult.

# Customizable DNS Server  / Port

For security schizos like myself who run local infrastructure like DNSCrypt with lots of caching, the concerns mentioned in https://github.com/MASQ-Project/Node/blob/master/node/docs/PORT_53.md  can be completely avoided without needing to disable locally running DNS servers. 

Therefore a good solution would be to allow delegation to a different dns server

**Comment by kauri-hero** [comment]
Thanks for your input! - you will be please to note this is being handled in #437
