### ISSUE TITLE
Add Base Chains - Sepolia & Mainnet

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/Node#430]
Support Base mainnet chain and Base Sepolia testnet

This will require Sepolia (ETH testnet) deployment for tMASQ, which can also replace the deprecated Ropsten chain thats still in Node code.

Note that ETH is the gas token native to Base chain, just like Ethereum mainnet

### ETH Sepolia:
Chain ID: 11155111 (0xaa36a7 is the hexcode)
[tMASQ Contract Creation: 0x574338FFb9471C7a260e338478409Ed0F8900ea5](https://sepolia.etherscan.io/tx/0xdeae49cfc274192d087656b549162e956dea347bcbf733ade9a5b46226a909d2)
Block Height: 6615411

### Base Sepolia:
Chain ID: 84532 (0x14a34 is the hexcode)
[tMASQ Contract Creation: 0x898E1cE720084A902Bc37dD822eD6D6a5F027E10](https://sepolia.basescan.org/tx/0xf689f21d9118b71a5c1ffdf741a4b1c36dfae2ffee36de56a087ba927d1243a8)
Block Height: 14732730

**Comment by kauri-hero** [comment]
updated with chain info @bertllll to work on the testchains ;-)

**Comment by bertllll** [comment]
I'm gonna create a new card that concentrates only on the matter of the Base chain. It's more urging. After that is done, I'll come back to this card to finish it by tearing Ropsten away and adding ETH Sepolia in.

**Comment by kauri-hero** [comment]
This will handle card: https://github.com/MASQ-Project/Node/issues/433
