### ISSUE TITLE
Disable `entry_dns`

### ISSUE THREAD

**Issue by utkarshg6** [MASQ-Project/Node#524]
The implementation of this card will free port 53 on Mac. However, this is not a permanent solution, as it disables the use of `entry_dns` in the code. A separate card should be created to re-enable `entry_dns` and provide a toggle for its functionality.

**Comment by kauri-hero** [comment]
@utkarshg6 is this related to card #437 in the Awaiting Dev column?

I think we need to be careful about fully disabling this unless we know the consequences of this in production.
I am unsure what reliance macOS has on this port 53 and we need to test to make sure MASQ Node will still operate as it does now without user having to do anything different
