### ISSUE TITLE
Investigate HTTP Headers with Node

### ISSUE THREAD

**Issue by kauri-hero** [MASQ-Project/Node#551]
Bert
I've got reasons to believe that the common practice for web servers has changed lately in some aspects and they've become more strict at evaluating if the inbound requests seem malicious. They most likely focus on the http header of those and try to see if they contain certain fields filled in with proper entries. I was inspired for this investigation by an issue with a Node's integration test contacting an actual web server, which Vojta had to be dealing with in the pursuit of a fix, and where he saw an error code 403 coming back from the server. It was later figured out that the difference that made the server satisfied, after the formerly minimally populated request, was when he proceeded to the appearance of a valid request which was tested aside on a browser, shaped up by it with more fields present. Such a copied header was the key to fixing the newly troublesome test. 

I later had to think of it and it motivated me to check the place in our code where we use the so called ClientRequestPayloadFactory which is a class responsible for preserving the original request, that comes into the Node from the browser, in a structured form, so that important pieces of information from there will be remembered and a reconstruction of it as a new request can be done later on so that it can be sent from the place of the exit Node towards the actual targeted server.

I believe that the issue we're having is in the portion of information we care in the original request and what other portion we give up. It seemed to me that we cared only about maybe two fields out of maybe a dozen which occur in the browser-generated requests. If we drastically simplify the http header by leaving out all or at least some of the other fields, we probably inadvertently make our reconstructed requests suspiciously simple and the servers tend to not to take them seriously or simply they might be programmed to assume they are dictated by a bot.

**Comment by kauri-hero** [comment]
Test Plan:

Use MASQ Browser and set up some testing to inspect the HTTP headers to inspect if anything is being retained or modified when using MASQ.

httpbin.org might be a place to check

**Comment by bertllll** [comment]
Was stupid of me to look at it like this... The requests are encrypted. Closing the issue.
